---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytuesdayR)
library(skimr)
```

```{r}
tuesdata <- tt_load(2021, week = 21)

survey <- tuesdata$survey
```

## cleaning country

```{r}
survey_clean <- survey %>% 
  mutate(
    country_clean = case_when(
      country %in% c("the United States", "the united states",
                     "THE united States", "the UNITED STATES",
                     "THE UNITED STATES", "The United States") ~ "USA"
    )
  )
```

would be cool to write a function that makes all of this a whole lot easier

```{r}
as_tibble(binary_strings(2))
```


```{r}
# binary string generator

binary_strings <- function(n, digits = c('0','1')) {
  if (n <= 0) return(matrix(0,0,0))
  if (n == 1) return(matrix(digits, 2))
  x <- binary_strings(n - 1)
  rbind(cbind(digits[1], x), cbind(digits[2], x))
}


name_variety <- function(name) {
  
  # separate string into its individual words
  
  words <- str_to_lower(str_split(name, " ")[[1]])
  
  # create bistrings
  
  n <- length(words)
  
  binary_tibble <- as_tibble(binary_strings(n), .name_repair = "unique")
  
  # create placeholder tibbles to be filled with modified strings
  
  full_word_cap <- binary_tibble
  first_letter_cap <- binary_tibble
  
  for (row in 1:nrow(binary_tibble)) {
     for (col in 1:n) {
      if (binary_tibble[row, col] == '0') {
        first_letter_cap[row, col] <- words[col]
        full_word_cap[row, col] <- words[col]
      } else {
        first_letter_cap[row, col] <- paste0(str_to_upper(str_sub(words[col], 1, 1)), str_sub(words[col], 2, -1))
        full_word_cap[row, col] <- str_to_upper(words[col])
      }

     }
  }
  
  # right now each word is a different column so we'd like to the unite the columns with a space as the seperator
  
  first_letter_cap <- unite(first_letter_cap, phrase, 1:ncol(first_letter_cap), sep = " ")
  full_word_cap <- unite(full_word_cap, phrase, 1:ncol(full_word_cap), sep = " ")
  
  # remove any duplicates
  
  final_phrases <- rbind(first_letter_cap, full_word_cap) %>% 
    distinct(.keep_all = T)
  
   if (stringr::str_detect(name, "'")) {
     
     to_add <- apos_rm(final_phrases)
     
     final_phrases <- rbind(final_phrases, to_add)
     
   }
  
  
  
  # turn our dataframe into a vector where each object is a string
  
  unlist(final_phrases, use.names = F)
  
}



```



```{r}
test <- tibble(
  names = c("clara's", "frank's", "tim's"),
  last = c("hershey's", "noah's", "thank's")
)
```

```{r}
for (i in 1:nrow(test)) {
  for (j in 1:ncol(test)) {
    
    test[i, j] <- str_remove_all(test[[i,j]], "'")
    
  }
}

apos_rm <- function(df) {
  
  test <- df
  
  for (i in 1:nrow(test)) {
    for (j in 1:ncol(test)) {
    
      test[i, j] <- str_remove_all(test[[i,j]], "'")
    
      }
  }
  
  test
  
}
  
```


```{r}
messy_string <- function(string, stop = F) {
  
  if (stringr::str_detect(string, "-")) {
    
    string2 <- stringr::str_replace_all(string, "-", " ")
    
    final_phrases <- name_variety(string2)
    final_phrases2 <- name_variety(string2)
    
    final_phrases2 <- final_phrases2 %>% 
      map_chr(~stringr::str_replace_all(.x, " ", "-"))
    
    ret <- c(final_phrases, final_phrases2)
    
  } else {
    
    ret <- name_variety(string)
    
  }
  

  
  
  
}
```

```{r}
test %>% 
  map_chr(~str_replace(.x, " ", "-"))
```


```{r}
library(tidytext)

stop_words
```





