---
title: "tidycoffee"
output: html_document
---

```{r}
coffee_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv')
```

```{r}
library(tidyverse)
library(dplyr)
library(ggridges)
library(GGally)
library(patchwork)
library(forcats)

coffee <- coffee_ratings %>%
  mutate(country_of_origin = fct_recode(
    country_of_origin,
    "Hawai‘i" = "United States (Hawaii)",
    "Tanzania" = "Tanzania, United Republic Of")
  )
```

```{r}
data <- coffee %>%
  group_by(country_of_origin) %>%
  count() %>%
  filter(n > 30) %>%
  left_join(coffee)

order_to <- data %>%
  group_by(country_of_origin) %>%
  summarize(mean(acidity)) %>%
  arrange(desc(`mean(acidity)`)) %>%
  pull(country_of_origin)
```

```{r}
data$country_of_origin <- factor(
  data$country_of_origin,
  levels = order_to)
```

```{r}
ggplot(data, 
       aes(x = acidity,
           y = country_of_origin,
           fill = country_of_origin)) +
  ggridges::geom_density_ridges(scale = 0.95) 
```

```{r}
ggplot(data, 
       aes(x = country_of_origin, 
           y = acidity)) +
  geom_boxplot()
```

```{r}
data1<-data%>%
  group_by(country_of_origin) %>%
  summarise(med = median(acidity)) %>%
  left_join(data)
```


```{r}
data_sorted <- data1 %>%
  mutate(country_of_origin = fct_reorder(country_of_origin, med)) %>%
  filter(acidity > 6)

```

```{r}
library(showtext)
library(ggbeeswarm)
library(ggsci)
font_add_google("Poppins", "Poppins")
font_add_google("Roboto Mono", "Roboto Mono")
showtext_auto()

ggplot(data_sorted, aes(x=country_of_origin, y= acidity)) +
  geom_violin(color="chocolate4", 
              fill="darkgoldenrod", 
              alpha =0.5,
              draw_quantiles = c(0.5)) +
  coord_flip() +
  scale_y_continuous(limits = c(5, 9),
                     expand = c(0.005, 0.005)) +
  theme(legend.position = "none", 
        axis.title.x = element_text(color = "black", 
                                    size = 10, 
                                    vjust = -0.35, 
                                    margin = margin(10, 0, 10, 0)), 
        axis.title.y = element_text(color= "black", 
                                    size = 10, 
                                    vjust =0.35, 
                                    margin = margin(0, 10, 0, 10)), 
        panel.background = element_rect(fill= "bisque2"), 
        plot.background = element_rect(fill = "bisque2"),
        axis.text.x = element_text(color = "black"), 
        axis.text.y = element_text(color = "black"), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        plot.title= element_text(size=14,
                                 face = "bold", 
                                 margin = margin(10, 0, 5, 0))) +
  labs(x="Country of Origin", 
       y = "Acidity Rating", 
       title = "Acidity Distribution of Coffee by Country",
       subtitle = "Only countries with n>30 were included")

```

```{r}
ggplot(data_sorted, aes(x = country_of_origin, y = acidity))+
  geom_quasirandom(alpha = 0.25, width = 0.3)+
  coord_flip() +
  scale_y_continuous(limits = c(5, 9),expand = c(0.005, 0.005))+
  theme(legend.position = "none", axis.title.x = element_text(color = "black", size = 10, vjust = -0.35, margin = margin(10,0,10,0)), axis.title.y = element_text(color= "black", size = 10, vjust =0.35, margin = margin(0,10,0,10)), panel.background = element_rect( fill= "bisque2"), plot.background = element_rect( fill = "bisque2"),axis.text.x = element_text(color="black"), axis.text.y = element_text(color="black"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),plot.title= element_text(size=14,face = "bold", margin = margin(10,0,5,0)), plot.margin=unit(c(0,2,0,2), "cm"))+
  labs(x="Country of Origin", y = "Acidity Rating", title = "Acidity Distribution of Coffee by Country",subtitle = "Only countries with n>30 were included")+
  scale_y_continuous(limits = c(5, 9),expand = c(0.005, 0.005)) +
  theme(legend.position = "none", 
        axis.title.x = element_text(color = "black", 
                                    size = 10, 
                                    vjust = -0.35, 
                                    margin = margin(10, 0, 10, 0)), 
        axis.title.y = element_text(color = "black", 
                                    size = 10, 
                                    vjust = 0.35, 
                                    margin = margin(0, 10, 0, 10)), 
        panel.background = element_rect( fill= "bisque2"), 
        plot.background = element_rect( fill = "bisque2"),
        axis.text.x = element_text(color = "black"), 
        axis.text.y = element_text(color = "black"), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        plot.title= element_text(size = 14, face = "bold", margin = margin(10, 0, 5, 0)))+
  labs(x="Country of Origin", 
       y = "Acidity Rating", 
       title = "Acidity Distribution of Coffee by Country",
       subtitle = "Only countries with n>30 were included")


```

