---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytuesdayR)
```

## loading data in

```{r}
tuesdata <- tidytuesdayR::tt_load(2021, week = 26)

parks_raw <- tuesdata$parks
```

```{r}
parks_raw %>% 
  count(year, sort = T) 
  

parks_allyrs <- parks_raw %>% 
  count(city, sort = T) %>% 
  filter(n == 9) %>% 
  select(city) %>% 
  pull()
  
```

## cleaning percents and dollar signs

```{r}
parks <- parks_raw %>% 
  mutate(park_pct_city_data = parse_number(park_pct_city_data)) %>% 
  mutate(pct_near_park_data = parse_number(pct_near_park_data)) %>% 
  mutate(spend_per_resident_data = parse_number(spend_per_resident_data))

parks %>% 
  ggplot(aes(park_pct_city_data)) +
  geom_histogram()

parks %>% 
  filter(city %in% parks_allyrs) %>% 
  group_by(city) %>% 
  summarise(mean_rank = mean(rank)) %>% 
  mutate(city = fct_reorder(city, -mean_rank)) %>% 
  ggplot(aes(x = city, y = mean_rank)) +
  geom_col(fill = "midnightblue") +
  labs(y = "Mean rank from 2012-2020") +
  coord_flip() +
  theme_minimal()

```



Just a small note to look into bayesian optimization a bit more.
  - one note is that when dealing with tuning hyper-parameters, a brute force method isn't always doable, and so bayesian
    optimization attempts to solve this problem!