---
title: "tidytransit"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytuesdayR)
```

```{r}
data <- tt_load(2021, week = 2)

transit <- data$transit_cost %>% 
  select(-reference, -source1, -source2)
  
```

```{r}
# exploration

count(transit, country, sort = T) # looks like there are 57 countries total

count(transit, start_year) # 67 NAs, earliest 1982, latest 2025 (must be planning)

count(transit, end_year, sort = T) # 71 NAs, earliest 1987, latest 2030

transit %>% 
  filter(
    is.na(start_year),
    is.na(end_year)
    ) # looks like there are 59 occurences of both start and end year missing

## I think for the remaining cases where just one year is missing, i'll try to impute the missing data

count(transit, year, sort = T) 
# wonderfully we have no missing data for the midpoint of the project
# so we can fix some of the NA's just with that


```



```{r}
## fixing missing year data

cols <- c("start_year","end_year")
transit[cols] <- sapply(transit[cols], as.numeric)

# when start year is missing but end year is not

transit1 <- transit %>% 
  filter(is.na(start_year), !is.na(end_year)) %>% 
  mutate(diff = end_year -year) %>% 
  mutate(start_year = year - diff) %>% 
  select(-diff)

# when end year is missing but start year is not

transit2 <- transit %>% 
  filter(!is.na(start_year), is.na(end_year)) %>%
  mutate(diff = year - start_year) %>%  
  mutate(end_year = year - diff) %>%  # any of these appear to be shorter than 1 year projects, wow!
  select(- diff)
  
transit %>% 
  filter(!is.na(start_year), !is.na(end_year)) %>% 
  mutate(diff = end_year - start_year) %>% 
  select(start_year, end_year, diff) %>% 
  summarise(diff = median(diff)) 
  # median diff is 5, so I'll use that for the 59 missing ones

transit3 <- transit %>% 
  filter(is.na(start_year), is.na(end_year)) %>% 
  mutate(diff = 5) %>% 
  mutate(start_year = year - diff,
         end_year = year + diff) %>% 
  select(-diff)

transit4 <- transit %>% 
  filter(!is.na(start_year), !is.na(end_year))

transit_final <- rbind(transit1, transit2, transit3, transit4)

```


```{r}
# the tunnel_per column has the % character but id rather just keep the variable as a double
transit_final <- transit_final %>% 
  filter(!is.na(real_cost)) %>% 
  mutate(tunnel_per = str_remove(tunnel_per, "%"),
         tunnel_per = as.double(tunnel_per),
         real_cost = as.double(real_cost))


transit_final <- transit_final %>% 
  mutate(duration = end_year - start_year) %>% 
  mutate(decade = year - (year %% 10)) %>% 
  mutate(duration = case_when(duration == 0 ~ 0.5, T ~ duration))
  
```


# plotting

```{r}
transit_final %>% 
  filter(decade != 1980) %>% 
  ggplot(aes(x = duration, y = log(real_cost))) +
  geom_hex(bins = 10, alpha = 0.8) +
  facet_wrap(~decade) +
  theme_minimal() +
  labs(x = "Duration in Years", y = "Logged Real Cost")
```


```{r}
library(tidymodels)

set.seed(0)
initial <- initial_split(transit_final, strata = duration)

train <- training(initial)
test <- testing(initial)

set.seed(99)
folds <- vfold_cv(train, strata = duration)
folds
```

```{r}
tree_spec <- decision_tree()
```







