---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytuesdayR)
```


```{r}
dat <- tt_load(2021, week = 3)

artwork_raw <- dat$artwork
artists_raw <- dat$artists
```

## Artwork

```{r}
artwork_raw %>% 
  select(id:units) %>%
  count(accession_number, id, sort = T) %>% 
  filter(n > 1)

# so id and accession_number are redundant, we can just keep one

artwork_raw %>% 
  count(artist, sort = T) %>% 
  filter(!str_detect(artist, ",")) 

# there are 55 artist names that don't follow the convention
```

```{r}
# British school is written in a bunch of weird ways so i made it consistent here
artwork <- artwork_raw %>% 
  mutate(
    artist = case_when(
      str_detect(artist, "\\.?British") ~ "British School",
      T ~ artist)
    )

# other than british school the other observations with unusual names are kind've anomalies and have very few
# occurences so I'm going to drop them

dropped_names <- artwork %>% 
  count(artist, sort = T) %>% 
  filter(!str_detect(artist, ",")) %>% 
  filter(artist != "British School") %>% 
  select(artist) %>% 
  pull()

# a `not in` function
'%!in%' <- function(x,y)!('%in%'(x,y))

# dropping the weird names
artwork <- artwork%>% 
  filter(artist %!in% dropped_names) %>% 
  separate(artist, into = c("name1", "name2"), sep = ",") %>% 
  # i'm doing this mutate step because British school will create NAs in the separate call
  mutate(
    name2 = case_when(
    !is.na(name2) ~ name2,
    is.na(name2) ~ "\n"
      )
    ) %>% 
  select(accession_number:units)

# lump artistRole
artwork <- artwork %>% 
  mutate(artistRole = fct_lump_min(artistRole, 100)) 
  
# dimension is a bit redundant because all the info we really care about in the dimension column
# is more nicely available in the height, width, depth columns
# something to note is that there are 2381 NAs which isn't a huge amount given the size of the data set,
# but it is still noteworthy

artwork <- artwork%>% 
  #count(units, sort = T)  almost entirely mm
  select(-dimensions) %>% 
  rename(creationYear = year) # for clarity

# I don't really know what to do with the creditLine column but i'll keep it since it seems interesting
# another not is that separating the name column was messy and it could be better to not do that step..

```

## Artists

```{r}
View(artists_raw)

artists_raw <- artists_raw %>% 
  select(-url)


artists_raw %>% 
  count(yearOfBirth)

artists_raw %>% 
  count(yearOfBirth) %>%
  ggplot(aes(x = yearOfBirth, y = n)) + 
  geom_point()

deathy <- artists_raw %>% 
  count(yearOfDeath)

birthy <- artists_raw %>% 
  count(yearOfBirth)

# I really like this plot
# I find the dip pretty interesting

# findings max's

# 1936
birthy %>% 
  filter(n > 40)

# 2005
deathy %>% 
  filter(n > 30)

# so many spaces!
ggplot(deathy, aes(yearOfDeath, n)) +
  geom_point(
    color = "midnightblue",
    alpha = 0.5,
    size = 2
    ) +
  geom_point(
    data = birthy,
    aes(yearOfBirth, n),
    color = "red", 
    alpha = 0.5,
    size = 2
    ) +
  geom_segment(
    x = 2005, xend = 2005,
    y = 0, yend = 55,
    color = "midnightblue",
    size = 2,
    alpha = 0.3,
    linetype = "dashed"
    ) +
  annotate(
    "text",
    label = "1936",
    x = 1936, y = 58,
    color = "red"
    ) +
  geom_segment(
    x = 1936, xend = 1936,
    y = 0, yend = 55,
    color = "red",
    size = 2,
    alpha = 0.3,
    linetype = "dashed"
    ) +
  annotate(
    "text",
    label = "2005",
    x = 2005, y = 58,
    color = "midnightblue"
    ) +
  ylim(0, 60) +
  labs(x = "Year",
       title = "Comparison of Year of Death (purple) and  \n Year of Birth (red) counts") +
  theme_minimal() 
```

### Modeling (following silge video)

```{r}
library(tidymodels)
theme_set(theme_minimal())
View(artwork_raw)
```


```{r}
# weird bimodal distribution
artwork_raw %>% 
  ggplot(aes(year)) +
  geom_histogram(alpha = 0.8, fill = "midnightblue")

tate_df <- artwork_raw %>% 
  filter(year > 1750) %>% 
  select(year, medium) %>% 
  na.omit() %>% 
  arrange(year)
```


```{r}
library(tidytext)

# most common words in medium
tate_df %>% 
  unnest_tokens(word, medium) %>% 
  count(word, sort = T)
```


```{r}
set.seed(50)
art_split <- initial_split(tate_df, strata = year)
test <- testing(art_split)
train <- training(art_split)

set.seed(34)
art_folds <- vfold_cv(train, strata = year)
```

```{r}
library(textrecipes)

art_rec <- recipe(year ~ medium, data = train) %>% 
  step_tokenize(medium) %>% 
  step_stopwords(medium) %>% 
  step_tokenfilter(medium, max_tokens = 500) %>% 
  step_tfidf(medium) 
```

```{r}
sparse_bp <- hardhat::default_recipe_blueprint(composition = "dgCMatrix")

lasso_spec <- linear_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")

art_wf <- workflow() %>% 
  add_recipe(art_rec, blueprint = sparse_bp) %>% 
  add_model(lasso_spec)
```

```{r}
doParallel::registerDoParallel()

lambda_grid <- grid_regular(penalty(range = c(-3, 0)), levels = 20)

lasso_results <- tune_grid(
  art_wf,
  resamples = art_folds,
  grid = lambda_grid
)
```

### evaluate model

```{r}
autoplot(lasso_results)
best_rmse <- select_best(lasso_results, "rmse")

final_lasso <- finalize_workflow(art_wf, best_rmse)
```


```{r}
art_final <- last_fit(final_lasso, art_split)
```

```{r}
library(vip)

art_vip <- pull_workflow_fit(art_final$.workflow[[1]]) %>% 
  vi()
  
art_vip %>% 
  group_by(Sign) %>% 
  slice_max(abs(Importance), n = 20) %>% 
  ungroup() %>% 
  mutate(
    Variable = str_remove(Variable, "tfidf_medium_"),
    Importance = abs(Importance),
    Variable = fct_reorder(Variable, Importance),
    Sign = if_else(Sign == "POS", "more in later art", "more in earlier art")
  ) %>% 
  ggplot(aes(Importance, Variable, fill = Sign)) +
  geom_col(show.legend = F) +
  facet_wrap(~Sign, scales = "free") +
  labs(y = "")

```

```{r}
collect_predictions(art_final) %>% 
  ggplot(aes(year,.pred)) +
  geom_abline(lty = 2, color = "grey50", size = 1.5) +
  geom_point(alpha = 0.3, size = 1.5, color = "midnightblue") +
  coord_fixed()
```

```{r}
# looking at where the model messed up the most
collect_predictions(art_final) %>% 
  bind_cols(test %>% select(medium)) %>% 
  filter(abs(year - .pred) > 100)
```








