---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(tidytuesdayR)
```

```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 22)

cocktails_raw <- tuesdata$cocktails
```

```{r}
# cleaning glass

cocktails_v1 <- 
  cocktails_raw %>%
  mutate(glass = str_to_lower(glass),
         glass = str_replace_all(glass, " ", "_"),
         # looks like there is a margarita/coupette and margarita
         glass = str_replace(glass, "margarita/coupette_glass", "margarita_glass")) %>%
  select(-date_modified, -drink_thumb, -iba, -video)

# cleaning alcoholic

cocktails_v2 <-
  cocktails_v1 %>% 
  mutate(alcoholic = str_to_lower(alcoholic),
         alcoholic = str_replace_all(alcoholic, " ", "_"),
         # just changed the NA's to unknown to keep data full
         alcoholic = replace_na(alcoholic, "unknown"))

# cleaning ingredient

# had 333 different ingredients before
# had 306 after, so we cleaned up some discrepancy which is good
cocktails_v3 <-
  cocktails_v2 %>%
  mutate(ingredient = str_to_lower(ingredient),
         ingredient = str_replace_all(ingredient, " ", "_")) 

# cleaning measure

# id like an `amount` and `unit` column, but it is veryyyy messy
# it looks like we need 3 columns total, the two aforementioned and a either `TRUE` to indicate original
# ingredient, or if its another ingredient
# you can highlight text and press " and it puts it in quotes!

cleaned_oz <-
  cocktails_v3 %>%
   # I have a space here to avoid things like frozen
  filter(str_detect(measure, " oz")) %>% 
  # i was annoyed with writing a regex for patterns with / in it so i just replaced all / with sl
  mutate(measure = str_replace(measure, "/", " sl "),
         measure = str_to_lower(measure),
         # this was an abnormal entry so I changed it by hand
         measure = str_replace(measure, "70ml sl 2fl oz", "2 oz")) %>%
  # here is a horrible regex, but it gets the job done!
  extract(
    measure,
    into = c("amount", "unit", "extra"),
    regex = "([0-9]\\.?-?[0-9]?[0-9]?\\s?[0-9]?\\s?s?l?\\s?[1-9]?\\s?[1-9]?[0-9]?)(oz)(\\s[a-z].*)?"
    ) %>%
  # changing sl back to /
  mutate(amount = str_replace(amount, " sl ", "/")) %>% 
  # separating the amount column into two parts, to deal with fractions individually
  separate(amount, into = c("num","frac"), sep = " ") %>%
  # changed the frac column to doubles 
  mutate(frac = sapply(frac, function(x) eval(parse(text=as.character(x))))) %>%
  # i hand changed the fractions in num because there were entries like 2-3 
  # there's definitely a better way to do this, but this works fine for this small exercise
  mutate(num = case_when(num == "1/2" ~ "0.5",
                         num == "3/4" ~ "0.75",
                         num == "1/3" ~ "0.33",
                         num == "1/4" ~ "0.25",
                         num == "2/3" ~ "0.66",
                         T ~ num)
         ) %>%
  mutate(frac = str_replace(frac, "NULL", "0"),
         frac = as.double(frac),
         # a way to deal with - and adding up fractions
         amount = case_when(str_detect(num, "-") ~ num,
                            T ~ as.character((as.double(num) + frac)))
         ) %>% 
  select(-num, -frac) %>%
  # just arranging variables in a nice way
  mutate(amount = as.double(amount))


# clean shots

cleaned_shot <- cocktails_v3 %>% 
  filter(str_detect(measure, " shot")) %>% 
  mutate(measure = str_to_lower(measure)) %>% 
  # even though it leaves some grammatical errors, i'm going to change all shots to shot for consistency
  mutate(measure = str_replace(measure, "shots", "shot")) %>% 
  extract(
    measure,
    into = c("amount", "unit", "extra"),
    regex = "([0-9]\\.?-?[0-9]?[0-9]?\\s?[0-9]?\\s?s?l?\\s?[1-9]?\\s?[1-9]?[0-9]?)(shot)(\\s[a-z].*)?"
    ) %>%
  mutate(amount = as.double(amount))


cocktails_v3 %>%
                                       
```

